// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('phonecat', ['phonecatFilters', 'phonecatServices']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/phones', {
        templateUrl: 'partials/phone-list.html',
        controller: PhoneListCtrl
      }).when('/phones/:phoneId', {
        templateUrl: 'partials/phone-detail.html',
        controller: PhoneDetailCtrl
      }).otherwise({
        redirectTo: '/phones'
      });
    }
  ]);

}).call(this);
