// Generated by CoffeeScript 1.4.0
(function() {

  this.PhoneListCtrl = function($scope, Phone) {
    $scope.phones = Phone.query();
    return $scope.orderProp = 'age';
  };

  this.PhoneListCtrl.$inject = ['$scope', 'Phone'];

  this.PhoneDetailCtrl = function($scope, $routeParams, Phone) {
    $scope.phone = Phone.get({
      phoneId: $routeParams.phoneId
    }, function(phone) {
      return $scope.mainImageUrl = phone.images[0];
    });
    return $scope.setImage = function(imageUrl) {
      return $scope.mainImageUrl = imageUrl;
    };
  };

  this.PhoneDetailCtrl.$inject = ['$scope', '$routeParams', 'Phone'];

}).call(this);
