// Generated by CoffeeScript 1.4.0
(function() {

  describe('PhoneCat controllers', function() {
    beforeEach(function() {
      return this.addMatchers({
        toEqualData: function(expected) {
          return angular.equals(this.actual, expected);
        }
      });
    });
    beforeEach(module('phonecatServices'));
    describe('PhoneListCtrl', function() {
      var $httpBackend, ctrl, scope;
      scope = null;
      ctrl = null;
      $httpBackend = null;
      beforeEach(function() {
        return inject(function(_$httpBackend_, $rootScope, $controller) {
          $httpBackend = _$httpBackend_;
          $httpBackend.expectGET('phones/phones.json').respond([
            {
              name: 'Nexus S'
            }, {
              name: 'Motorola DROID'
            }
          ]);
          scope = $rootScope.$new();
          return ctrl = $controller(PhoneListCtrl, {
            $scope: scope
          });
        });
      });
      it('should create "phones" model with 2 phones fetched from xhr', function() {
        expect(scope.phones).toEqual([]);
        $httpBackend.flush();
        return expect(scope.phones).toEqualData([
          {
            name: 'Nexus S'
          }, {
            name: 'Motorola DROID'
          }
        ]);
      });
      return it('should set the default value of orderProp model', function() {
        return expect(scope.orderProp).toBe('age');
      });
    });
    return describe('PhoneDetailCtrl', function() {
      var $httpBackend, ctrl, scope, xyzPhoneData;
      scope = null;
      ctrl = null;
      $httpBackend = null;
      xyzPhoneData = function() {
        return {
          name: 'phone xyz',
          images: ['image/url1.png', 'image/url2.png']
        };
      };
      beforeEach(function() {
        return inject(function(_$httpBackend_, $rootScope, $routeParams, $controller) {
          $httpBackend = _$httpBackend_;
          $httpBackend.expectGET('phones/xyz.json').respond(xyzPhoneData());
          $routeParams.phoneId = 'xyz';
          scope = $rootScope.$new();
          return ctrl = $controller(PhoneDetailCtrl, {
            $scope: scope
          });
        });
      });
      return it('should fetch phone detail', function() {
        expect(scope.phone).toEqualData([]);
        $httpBackend.flush();
        return expect(scope.phone).toEqualData(xyzPhoneData());
      });
    });
  });

}).call(this);
